### ISSUE TITLE
Compiled VS2013 vs Compiled VS2015

### ISSUE THREAD

**Issue by halsten** [tandasat/Scavenger#4]
I tried to compile on both versions and still the same problem as the first Issue I submitted. Even while trying to load with DrvLoad. Same thing. Your compiled SYS file definitely looks different than the one generated from in both cases, and I am wondering if you did have a different version of the on uploaded here.

**Comment by SACHINRAI1986** [comment]
> I tried to compile on both versions and still the same problem as the first Issue I submitted. Even while trying to load with DrvLoad. Same thing. Your compiled SYS file definitely looks different than the one generated from in both cases, and I am wondering if you did have a different version of the on uploaded here.

**Comment by SACHINRAI1986** [comment]
All

**Comment by tandasat** [comment]
Came here through the notification. Closing this along with other 6-year-old issues as I do not think anybody cares.
